services:
  - type: web
    name: authenticam-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: "524288000"
      - key: PRIVATE_KEY_PATH
        value: ./keys/private.pem
      - key: PUBLIC_KEY_PATH
        value: ./keys/public.pem
