/**
 * fingerprint.js — Device Fingerprint Service for AuthentiCam
 *
 * The browser sends a raw fingerprint string (generated by frontend/lib/fingerprint.ts).
 * This module:
 *   1. Parses additional metadata from the request (User-Agent, IP, timestamp)
 *   2. Builds an enriched fingerprint object
 *   3. Computes a canonical SHA-256 hash for storage in the certificate
 *
 * The fingerprint_hash in the certificate allows verifiers to confirm the
 * recording was made on a known device — or flag it as UNKNOWN_DEVICE.
 *
 * @module fingerprint
 */

'use strict';

const crypto = require('crypto');

/**
 * Parse and enrich a raw client fingerprint string.
 *
 * @param {string} rawFingerprint — from frontend generateDeviceFingerprint()
 * @param {import('express').Request} req — Express request for server-side metadata
 * @returns {{ raw: string, userAgent: string, ipAddress: string, enrichedHash: string, components: object }}
 */
function parseClientFingerprint(rawFingerprint, req) {
    const userAgent = req?.headers?.['user-agent'] || 'unknown';
    const ipAddress = req?.ip || 'unknown';

    const components = {
        clientFingerprint: rawFingerprint || 'unknown',
        userAgent,
        ipAddress,
        serverTimestamp: new Date().toISOString(),
    };

    const canonical = JSON.stringify(components, Object.keys(components).sort());
    const enrichedHash = crypto.createHash('sha256').update(canonical).digest('hex');

    return {
        raw: rawFingerprint || 'unknown',
        userAgent,
        ipAddress,
        enrichedHash,
        components,
    };
}

/**
 * Build a fingerprint hash from arbitrary components.
 * Used when you already have extracted components.
 *
 * @param {object} components
 * @returns {string} SHA-256 hex hash
 */
function buildFingerprintHash(components) {
    const canonical = JSON.stringify(components, Object.keys(components).sort());
    return crypto.createHash('sha256').update(canonical).digest('hex');
}

/**
 * Compare a submitted fingerprint against a stored fingerprint hash.
 * Returns a match confidence score:
 *   - 'MATCH'    — hashes are identical
 *   - 'PARTIAL'  — raw fingerprint matches but enriched hash differs (IP change etc.)
 *   - 'MISMATCH' — completely different device
 *
 * @param {string} submittedRaw — raw fingerprint from current request
 * @param {string} storedRaw — raw fingerprint stored in certificate
 * @param {string} storedEnrichedHash — enriched hash stored in certificate
 * @param {object} currentComponents — current request components
 * @returns {{ verdict: 'MATCH'|'PARTIAL'|'MISMATCH', details: string }}
 */
function compareFingerprints(submittedRaw, storedRaw, storedEnrichedHash, currentComponents) {
    const currentHash = buildFingerprintHash(currentComponents);

    if (currentHash === storedEnrichedHash) {
        return { verdict: 'MATCH', details: 'Device fingerprint hash identical' };
    }

    if (submittedRaw && storedRaw && submittedRaw === storedRaw) {
        return {
            verdict: 'PARTIAL',
            details: 'Browser fingerprint matches but network/IP changed — possible different session',
        };
    }

    return {
        verdict: 'MISMATCH',
        details: 'Device fingerprint does not match — recording may be from a different device',
    };
}

module.exports = {
    parseClientFingerprint,
    buildFingerprintHash,
    compareFingerprints,
};
